version: '3.8'
services:
  postgres_db_mp3:
    image: postgres:16-alpine
    container_name: Mp3Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mp3Analytics
    ports:
      - '5432:5432'
    volumes:
      - postgres_db_mp3:/var/lib/postgresql/data
volumes:
  postgres_db_mp3:
